name: sandbox
description: "Personal page and sandbox"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Service Locator для упрощения работы с зависимостями
  get_it: ^8.0.1
  # Аннотации для упрощеения работы с get_it
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
    # Для запуска кодогенерации
  build_runner: ^2.4.15
  # Гереция кода для упрощения работы с GetIt
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true